### ISSUE TITLE
Strings are inlined into entry modules instead of _base.js

### ISSUE THREAD

**Issue by camwest** [cramforce/splittable#12]
Hey there, 

I have an issue with how CSS exported from modules is inlined. This might be an issue for closure compiler instead of splittable but I wanted to get your take on it first. See below for details:

```javascript
# a.js
import css from './css-module';

const style = document.createElement('style');
style.textContent = css;
document.body.appendChild(style);
```

```
# b.js
import css from './css-module';
const style = document.createElement('style');
style.textContent = css;
document.body.appendChild(style);
```

```
# css-module.js

const css = `
...huge amount of css
`;

export default css;
```

## Expected behaviour: 

* The string exported from css-module should be extracted into the _base.js and shared between the a.js and b.js entry point modules

## Actual behaviour:

* The string is inlined into a.js and b.js duplicating the contents across both modules.

**Comment by cramforce** [comment]
Very interesting problem! Like really! But please file in closure compiler
repo. It isn't entirely clear what is the right thing to do. Often keeping
base smaller is better even if delivering more bytes in total.
