### ISSUE TITLE
Progressive loading

### ISSUE THREAD

**Issue by matthewp** [cramforce/splittable#5]
It's not clear from the code or article if the supports progressive loading via `require.ensure` or `System.import` or something else. Would be good to add that to the readme, I think. Cool project!

**Comment by matthewp** [comment]
Maybe, to answer my own question, is that you would have a new entry for the lazy-loaded code and dynamically inject a `<script>` to load it.

**Comment by cramforce** [comment]
Right. Simple to wrap in a JS loader similar to require.ensure. But not
quite the same. The caller cannot get access to module object without
additional code. Might be worth adding that boilerplate by default.

**Comment by cramforce** [comment]
`System.import` is implemented.
