### ISSUE TITLE
Incorrectly transpiles classes

### ISSUE THREAD

**Issue by matthewp** [cramforce/splittable#8]
This input code:

```js
class MyWidget extends HTMLElement {
  connectedCallback(){
    console.log("hello world");
  }
}

window['customElements']['define']('my-widget', MyWidget);
```

Compiles to:

```js
function f(a, b) {
    function d() {}
    d.prototype = b.prototype;
    a.prototype = new d;
    a.prototype.constructor = a;
    for (var c in b)
        if (Object.defineProperties) {
            var e = Object.getOwnPropertyDescriptor(b, c);
            e && Object.defineProperty(a, c, e)
        } else
            a[c] = b[c]
}
function g(a) {
    HTMLElement.apply(this, arguments)
}
f(g, HTMLElement);
window.customElements.define("my-widget", g);
```

Note the `HTMLElement.apply`; you can't do that. It should instead transpile to: `return Reflect.construct(HTMLElement, arguments, this.constructor)`.  I think this still wouldn't work without a shim though.

Ideally there would be a way to turn *off* -> ES5 transpiling though, as it is more verbose than the ES6 equivalent.  Also, in this case by using Reflect.construct you would be doubling the number of objects that get created.  The ES class version is just better.

Maybe I should post an issue in Closure's issue tracker for this though?

**Comment by cramforce** [comment]
Yeah, nothing splittable can do about it. Closure certainly favors fast
over correct, although that transpile is pretty suspicious for various
reasons.

**Comment by matthewp** [comment]
I'm not sure why this code would be faster than the correct ES2015 version though.  Even if you replaced the HTMLElement.apply (which throws currently) with a Reflect.construct call it would be slower.

**Comment by cramforce** [comment]
Lets move to Closure Compiler github https://github.com/google/closure-compiler

**Comment by matthewp** [comment]
I posted https://github.com/google/closure-compiler/issues/2157, thanks!
